name: "Golang Checks"
run-name: "Checking go code at ${{ github.ref_name }}"

on:
  push:
    paths: 
      - '**.go'
      - go.mod
      - go.sum
      - .github/workflows/golang_checks.yaml
      - .github/actions/go-info/**
  workflow_dispatch:

jobs:
  
  go-test:
    name: Golang Test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Get Go info from repo"
        id: go
        uses: ./.github/actions/go-info
      
      - name: Set up Go ${{ steps.go.outputs.version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go.outputs.version }}

      - name: Run Unit Tests
        run: |
          go mod download
          go test ./... -v
  
  go-vet:
    name: Golang Vet
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Get Go info from repo"
        id: go
        uses: ./.github/actions/go-info
      
      - name: Set up Go ${{ steps.go.outputs.version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go.outputs.version }}

      - name: Run static analysis
        run: |
          go mod download
          go vet ./...
  
  go-vulncheck:
    name: Golang Vulncheck
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Get Go info from repo"
        id: go
        uses: ./.github/actions/go-info
      
      - name: Set up Go ${{ steps.go.outputs.version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go.outputs.version }}

      - name: Run Vulnerability checker
        run: |
          go mod download
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
  
  go-lint:
    name: Golang Lint
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Get Go info from repo"
        id: go
        uses: ./.github/actions/go-info
      
      - name: Set up Go ${{ steps.go.outputs.version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go.outputs.version }}

      - name: Run Linter
        run: |
          go mod download
          go install golang.org/x/lint/golint@latest
          golint ./...